Nouvement/config/routes.rb
Rails.application.routes.draw do
  resources :suggestions

  resources :friend_requests

  resources :locations

  get 'main/new'

  get 'main/main'

  devise_for :users
  resources :notifications

  resources :posts

  resources :check_ins

  resources :events

  post 'friend_requests/accept' => 'friend_requests#accept', as: :accept
  post 'friend_requests/reject' => 'friend_requests#reject', as: :reject

  post 'events/:id/suggest' => 'events#suggest', as: :suggest
  post 'events/:id/vote' => 'events#vote', as: :vote
  root 'main#main'

end

Nouvement/app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
	belongs_to :event
	belongs_to :location
end

Nouvement/app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :set_suggestion, only: [:show, :edit, :update, :destroy]

  # GET /suggestions
  # GET /suggestions.json
  def index
    @suggestions = Suggestion.all
  end

  # GET /suggestions/1
  # GET /suggestions/1.json
  def show
  end

  # GET /suggestions/new
  def new
    @suggestion = Suggestion.new
  end

  # GET /suggestions/1/edit
  def edit
  end

  # POST /suggestions
  # POST /suggestions.json
  def create
    @suggestion = Suggestion.new(suggestion_params)

    respond_to do |format|
      if @suggestion.save
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully created.' }
        format.json { render :show, status: :created, location: @suggestion }
      else
        format.html { render :new }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suggestions/1
  # PATCH/PUT /suggestions/1.json
  def update
    respond_to do |format|
      if @suggestion.update(suggestion_params)
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully updated.' }
        format.json { render :show, status: :ok, location: @suggestion }
      else
        format.html { render :edit }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suggestions/1
  # DELETE /suggestions/1.json
  def destroy
    @suggestion.destroy
    respond_to do |format|
      format.html { redirect_to suggestions_url, notice: 'Suggestion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suggestion
      @suggestion = Suggestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def suggestion_params
      params.require(:suggestion).permit(:num_votes)
    end
end

Nouvement/app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

Nouvement/app/views/suggestions/_form.html.erb
<%= form_for(@suggestion) do |f| %>
  <% if @suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suggestion.errors.count, "error") %> prohibited this suggestion from being saved:</h2>

      <ul>
      <% @suggestion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :num_votes %><br>
    <%= f.number_field :num_votes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Nouvement/app/views/suggestions/edit.html.erb
<h1>Editing suggestion</h1>

<%= render 'form' %>

<%= link_to 'Show', @suggestion %> |
<%= link_to 'Back', suggestions_path %>

Nouvement/app/views/suggestions/index.html.erb
<h1>Listing suggestions</h1>

<table>
  <thead>
    <tr>
      <th>Num votes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suggestions.each do |suggestion| %>
      <tr>
        <td><%= suggestion.num_votes %></td>
        <td><%= link_to 'Show', suggestion %></td>
        <td><%= link_to 'Edit', edit_suggestion_path(suggestion) %></td>
        <td><%= link_to 'Destroy', suggestion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Suggestion', new_suggestion_path %>

Nouvement/app/views/suggestions/new.html.erb
<h1>New suggestion</h1>

<%= render 'form' %>

<%= link_to 'Back', suggestions_path %>

Nouvement/app/views/suggestions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Num votes:</strong>
  <%= @suggestion.num_votes %>
</p>

<%= link_to 'Edit', edit_suggestion_path(@suggestion) %> |
<%= link_to 'Back', suggestions_path %>