Nouvement/config/routes.rb
Rails.application.routes.draw do
  resources :suggestions

  resources :friend_requests

  resources :locations

  get 'main/new'

  get 'main/main'

  devise_for :users
  resources :notifications

  resources :posts

  resources :check_ins

  resources :events

  post 'friend_requests/accept' => 'friend_requests#accept', as: :accept
  post 'friend_requests/reject' => 'friend_requests#reject', as: :reject

  post 'events/:id/suggest' => 'events#suggest', as: :suggest
  post 'events/:id/vote' => 'events#vote', as: :vote
  root 'main#main'

end

Nouvement/app/models/event.rb
class Event < ActiveRecord::Base
	enum state: [ :final, :draft ]
	belongs_to :organiser, class_name: "User"
	has_and_belongs_to_many :invited_users, class_name: "User", join_table: "invited_users_events"
	has_and_belongs_to_many :accepted_users, class_name: "User", join_table: "accepted_users_events"
	has_and_belongs_to_many :rejected_users, class_name: "User", join_table: "rejected_users_events"

	has_many :suggestions, foreign_key: 'event_id'
	has_many :suggested_locations, through: :suggestions

	has_one :final_location, class_name: "Location", foreign_key: "final_event_id"
	has_many :voters, class_name: "User", foreign_key: "voting_event_id"
end

Nouvement/app/controllers/events_controller.rb
require 'json'
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :suggest, :vote]
  before_action :authenticate_user!, only: [:index,:show,:new,:edit,:create,:update,:destroy]

  # GET /events
  # GET /events.json
  def index
    @accepted_events = current_user.accepted_events
    @invited_events = current_user.invited_events
    File.open("all_profiles.json", "w") {Event.all.collect { |p| { :location => p.location } }.to_json }
  end

  # GET /events/1
  # GET /events/1.json
  def show
    #if @event in current_user.invited_events || @event in current_user.accepted_events

    #else
    #  redirect_to root_path
    #end
  end

  # GET /events/new
  def new
    @event = Event.new
    #@users = User.search(params[:search])
    @users= current_user.friends
    @location = Location.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.state = params[:state]

    @user_ids = params[:user_ids]

    @event.organiser = current_user

    if params[:allowSuggestion] == '1'
      @event.allowsuggest = 1
    else
      @event.allowsuggest = 0
    end

    respond_to do |format|
      if @event.save
        
        if @user_ids!=nil
          @user_ids.each do |user_id|
            @invited_user = User.find_by(id: user_id)
            @invited_user.invited_events << @event
            AppMailer.new_invited_event(@event,@invited_user).deliver
            # Tom: add relationship between invited users and the event
            @n= Notification.create(content:"New Event created on "+@event.date.to_s+" at "+@event.time.to_s, readstate: 0)
            @invited_user.notifications << @n
            @n.event = @event
            @n.save
          end
        end

        @location_name = @event.location
        @loc = Location.find_by(name: @location_name)
        if @loc == nil
          @loc = Location.new(name: @location_name)
          @loc.save
        end

        @event.invited_users << current_user
        if @event.state == :final
          @event.final_location = @loc
          @event.save
        else
          @suggestion = Suggestion.create(location: @loc, event: @event, num_votes: 0)
        end

        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end


  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def suggest
    @location_name = params[:suggestion][:location]
    @loc = Location.find_by(name: @location_name)
    if @loc == nil
      @loc = Location.new(name: @location_name)
      @loc.save
    end

    @suggestion = Suggestion.create(location: @loc, event: @event, num_votes: 0)
    redirect_to @event
  end

  def vote
    @loc = Location.find_by(id:params['voted_location'])
    @s = Suggestion.find_by(event: @event, location: @loc)

    @s.num_votes += 1

    @s.save

    @event.voters << current_user
    
    redirect_to @event

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :time, :message, :location, :state)
    end
end

Nouvement/app/helpers/events_helper.rb
module EventsHelper
end

Nouvement/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :date %><br>
    <%= f.text_field :date, :class => "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :time %><br>
    <%= f.text_field :time, :class => "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :message %><br>
    <%= f.text_area :message, :class => "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :location %>
    <%= f.text_field :location , :id => "location", :class => "form-control" %>
  </div>

  <div class="field table">
    <% @users.each do |user| %>
      <% if user.id != current_user.id %>
      <tr>
        <td><%= check_box_tag 'user_ids[]', user.id %></td>
        <td><%= user.full_name %></td>
      </tr>
      <% end %>
    <% end %>
  </div>

  <div class="field form-group">
    <%= f.label :state %><br>
    <td>
      <%= radio_button_tag 'state', :final, true, :class => "radio" %>
      Final
    </td>
    <td>
      <%= radio_button_tag 'state', :draft, false, :class => "radio" %>
      Draft
    </td>
  </div>
  <br/>

  <%= check_box_tag 'allowSuggestion', 1, :class => "checkbox" %> 
  <%= 'allow friends to make suggestions' %> 
  <br/>
  <br/>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

Nouvement/app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

Nouvement/app/views/events/index.html.erb
<%= javascript_include_tag 'main.js' %>

<h1>Invited events</h1>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Message</th>
      <th>Location</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invited_events.each do |event| %>
      <tr>
        <td><%= event.date %></td>
        <td><%= event.time %></td>
        <td><%= event.message %></td>
        <td ><%= event.location %></td>
        <td><%= event.state %></td>
        <td><%= link_to 'Show', event, :id => "show" %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

Nouvement/app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

Nouvement/app/views/events/show.html.erb
<%= javascript_include_tag 'main.js' %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.time %>
</p>

<p>
  <strong>Message:</strong>
  <%= @event.message %>
</p>

<p>
  <strong>State:</strong>
  <%= @event.state %>
</p>

<% if @event.state == 'draft' %>
  <p>
    <% if not @event.voters.include?(current_user) %>
      <strong>Please vote for a place for this event:</strong>
      <%= form_for :vote, :url => vote_path, :method => 'post' do |f| %>
          <% @event.suggestions.each do |suggestion| %>
          <tr>
            <td><%= radio_button_tag 'voted_location', suggestion.location.id, false %></td>
            <td><%= suggestion.location.name %></td>
            <td><%= suggestion.num_votes %></td>
          </tr>
          <br/>
          <% end %>
          
          <br/>
          <div class="actions">
              <%= f.submit 'Vote' %>
          </div>
      <% end %>
    <%else%>
      <strong>Voting results:</strong>
      <% @event.suggestions.each do |suggestion| %>
          <tr>
            <td><%= suggestion.location.name %></td>
            <td><%= suggestion.num_votes %></td>
          </tr>
          <br/>
      <% end %>
    <% end %>
  </p>

    <% if (not @event.voters.include?(current_user)) && (@event.allowsuggest == 1) %>
      <strong>Suggest another place:</strong>
      <%= form_for :suggestion, :url => suggest_path, :method => 'post' do |f| %>
              <div class="input-group">
                <%= f.text_field :location %>
              <div class="actions">
                <%= f.submit 'Submit' %>
              </div>
      <% end %>
    <% end %>
<% else %>
    <p>
      <strong>Location:</strong>
      <%= @event.location %>
    </p>
<% end %>
<%= link_to 'Back', events_path %>