Nouvement/config/routes.rb
Rails.application.routes.draw do
  resources :suggestions

  resources :friend_requests

  resources :locations

  get 'main/new'

  get 'main/main'

  devise_for :users
  resources :notifications

  resources :posts

  resources :check_ins

  resources :events

  post 'friend_requests/accept' => 'friend_requests#accept', as: :accept
  post 'friend_requests/reject' => 'friend_requests#reject', as: :reject

  post 'events/:id/suggest' => 'events#suggest', as: :suggest
  post 'events/:id/vote' => 'events#vote', as: :vote
  root 'main#main'

end

Nouvement/app/models/check_in.rb
class CheckIn < ActiveRecord::Base
	belongs_to :user
	belongs_to :location
end

Nouvement/app/controllers/check_ins_controller.rb
class CheckInsController < ApplicationController
  before_action :set_check_in, only: [:show, :edit, :update, :destroy]

  # GET /check_ins
  # GET /check_ins.json
  def index
    @check_ins = CheckIn.all
  end

  # GET /check_ins/1
  # GET /check_ins/1.json
  def show
  end

  # GET /check_ins/new
  def new
    @check_in = CheckIn.new
  end

  # GET /check_ins/1/edit
  def edit
  end

  # POST /check_ins
  # POST /check_ins.json
  def create
    @check_in = CheckIn.new(check_in_params)
    @location = Location.find_by(id: params[:location_id])
    @check_in.location << @location
    @check_in.user << current_user

    respond_to do |format|
      if @check_in.save
        format.html { redirect_to @check_in, notice: 'Check in was successfully created.' }
        format.json { render :show, status: :created, location: @check_in }
      else
        format.html { render :new }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /check_ins/1
  # PATCH/PUT /check_ins/1.json
  def update
    respond_to do |format|
      if @check_in.update(check_in_params)
        format.html { redirect_to @check_in, notice: 'Check in was successfully updated.' }
        format.json { render :show, status: :ok, location: @check_in }
      else
        format.html { render :edit }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /check_ins/1
  # DELETE /check_ins/1.json
  def destroy
    @check_in.destroy
    respond_to do |format|
      format.html { redirect_to check_ins_url, notice: 'Check in was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check_in
      @check_in = CheckIn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_in_params
      params.require(:check_in).permit(:location, :date, :time)
    end
end

Nouvement/app/helpers/check_ins_helper.rb
module CheckInsHelper
end

Nouvement/app/views/check_ins/_form.html.erb
<%= form_for(@check_in) do |f| %>
  <% if @check_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check_in.errors.count, "error") %> prohibited this check_in from being saved:</h2>

      <ul>
      <% @check_in.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Nouvement/app/views/check_ins/edit.html.erb
<h1>Editing check_in</h1>

<%= render 'form' %>

<%= link_to 'Show', @check_in %> |
<%= link_to 'Back', check_ins_path %>

Nouvement/app/views/check_ins/index.html.erb
<h1>Listing check_ins</h1>

<table class="table-striped">
  <thead>
    <tr>
      <th>Location</th>
      <th>Date</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @check_ins.each do |check_in| %>
      <tr>
        <td><%= check_in.location %></td>
        <td><%= check_in.date %></td>
        <td><%= check_in.time %></td>
        <td><%= link_to 'Show', check_in %></td>
        <td><%= link_to 'Edit', edit_check_in_path(check_in) %></td>
        <td><%= link_to 'Destroy', check_in, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Check in', new_check_in_path %>

Nouvement/app/views/check_ins/new.html.erb
<h1>New check_in</h1>

<%= render 'form' %>

<%= link_to 'Back', check_ins_path %>

Nouvement/app/views/check_ins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @check_in.location %>
</p>

<p>
  <strong>Date:</strong>
  <%= @check_in.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @check_in.time %>
</p>

<%= link_to 'Edit', edit_check_in_path(@check_in) %> |
<%= link_to 'Back', check_ins_path %>